estacionameApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuario.urls')),
    path('', include('web.urls')),
]

usuario/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('users', views.UsuariosLista, name="index"),
    path('detalle/<str:pk>', views.UsuariosDetalle, name="detalle"),
    path('crear', views.UsuariosCrear, name="crear"),
    path('actualizar/<str:pk>/', views.UsuariosActualizar, name="actualizar"),
    path('eliminar/<str:pk>', views.UsuariosEliminar, name="eliminar"),
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('/form', views.postUsuario, name='formulario')

]

usuario/models.py
from django.db import models

# Create your models here.

class Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    password = models.CharField(max_length=12)
    email = models.CharField(max_length=100)
    edad = models.CharField(max_length=3)
    auto = models.CharField(max_length=100)
    estacionamiento = models.CharField(max_length=20)
    comuna = models.CharField(max_length=100)
    tipo_cliente = models.DateTimeField(auto_now_add=True)


    class Meta:
        db_table = 'Usuario'

    def __str__(self):
        return self.nombre
    

web/models.py
from django.db import models

# Create your models here.

web/forms.py
from django import forms


class UsuarioForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    password = forms.CharField(max_length=12)
    email = forms.CharField(max_length=100)
    edad = forms.CharField(max_length=100)
    auto = forms.CharField(max_length=100)
    estacionamiento = forms.CharField(max_length=100)
    comuna = forms.CharField(max_length=100)

usuario/views.py
from django.shortcuts import render
from .models import *
from .serializer import UsuariosSerializer
from rest_framework.response import Response
from rest_framework.decorators import api_view

# Create your views here.

#get all
@api_view(['GET'])
def UsuariosLista(request):
    users = Usuario.objects.all()
    serializer = UsuariosSerializer(users, many=True)
    return Response(serializer.data)

#get por id
@api_view(['GET'])
def UsuariosDetalle(request, pk):
    users = Usuario.objects.all(id=pk)
    serializer = UsuariosSerializer(users, many=False)
    return Response(serializer.data)

#crear user
@api_view(['POST'])
def UsuariosCrear(request):
    serializer = UsuariosSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
    else:
        return Response(serializer.errors)
    return Response(serializer.data)

#actualizar usuarios
@api_view(['POST'])
def UsuariosActualizar(request, pk):
    usuarios = Usuario.objects.get(id=pk)
    serializer = UsuariosSerializer(instance=usuarios, data=request.data)
    if serializer.is_valid():
        serializer.save()
    else:
        return Response(serializer.errors)
    return Response(serializer.data)

@api_view(['DELETE'])
def UsuariosEliminar(request, pk):
    users = Usuario.objects.get(id=pk)
    users.delete()

    return Response('Eliminado')

web/views.py
from django.urls import path
from . import views
import requests
from rest_framework.utils import json
from django.shortcuts import render
from .forms import UsuarioForm

app_name = 'web'

def index(request):
    response = requests.get('http://127.0.0.1:8000/usuarios/').json()
    return render(request, 'web/usuarioAPI.html', {
        'response': response
    })

def postUsuario(request):
    url = "http://127.0.0.1:8000/usuario/crear"
    form = UsuarioForm(request.POST or None)
    if form.is_valid():
        nombre = form.cleaned_data.get("nombre")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        edad = form.cleaned_data.get("edad")
        auto = form.cleaned_data.get("auto")
        estacionamiento = form.cleaned_data.get("estacionamiento")
        comuna = form.cleaned_data.get("comuna")
        print(nombre)
        print(password)
        print(email)
        print(edad)
        print(auto)
        print(estacionamiento)
        print(comuna)
        data = {'nombre': nombre, 'password': password, 'email': email, 'edad': edad, 'auto': auto, 'estacionamiento': estacionamiento, 'comuna': comuna}
        headers = {'Content-type': 'application/json', }
        response = requests.post(url, data=json.dumps(data), headers=headers)
        return render(request, 'web/form.html', {
            'response': response
        })

web/templates/web/form.html
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Formulario enviado</title>
    </head>
    <body>
        <Formulario>Formulario Enviado</Formulario>
    </body>
</html>

web/templates/web/usuarioAPI.html
<form action="{% url 'web:formulario' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p> 
        <label for="id_nombre">Nombre:</label>
        <input id="id_nombre" type="text" name="nombre" maxlength="100" required>
    </p>
    <p>
        <label for="id_precio">Password:</label>
        <input id="id_precio" type="password" name="precio" maxlength="12" required>
    </p>
    <p>
        <label for="id_stock">Email:</label>
        <input id="id_stock" type="email" name="stock" maxlength="100" required>
    </p>
    <p> 
        <label for="id_nombre">Edad:</label>
        <input id="id_nombre" type="text" name="nombre" maxlength="100" required>
    </p>
    <p> 
        <label for="id_nombre">Auto:</label>
        <input id="id_nombre" type="text" name="nombre" maxlength="100" required>
    </p>
    <p> 
        <label for="id_nombre">Estacionamiento:</label>
        <input id="id_nombre" type="text" name="nombre" maxlength="100" required>
    </p>
    <p> 
        <label for="id_nombre">Comuna:</label>
        <input id="id_nombre" type="text" name="nombre" maxlength="100" required>
    </p>
  <button type="submit">Crear productos</button>
</form>


<ul>
    {% for obj in response %}
        <li>{{ obj.id }} - {{ obj.nombre }} {{ obj.email }}</li>
    {% endfor %}
</ul>